@echo off
cls
echo ==================================================
echo STARTING FULL BUILD (Win32/Win64 - Debug/Release)
echo ==================================================

echo [1/4] Building Win32 Debug...
call mk_rd_dev.bat debug
echo ...
echo [2/4] Building Win64 Debug...
call mk_rd_dev64.bat debug
echo ...
echo [3/4] Building Win32 Release...
call mk_rd_dev.bat release
echo ...
echo [4/4] Building Win64 Release...
call mk_rd_dev64.bat release
echo ...

echo ==================================================
echo FINISH
echo ==================================================
pause
