name: ci-windows-mingw

env:
  CI: GITHUB

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
  schedule:
    - cron: "42 3 * * *"
      timezone: "Europe/Moscow"
  repository_dispatch:
    types: [dispatch-event]

jobs:
  ci-job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        dll: [ON, OFF]
        without_crt: [ON, OFF]
        os: [windows-latest]
        exclude:
          - build-type: Debug
            dll: OFF
          - build-type: Release
            without_crt: ON
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: true
#    - name: Update mingw64
#      run: choco upgrade mingw -y --no-progress
    - name: ci-step
      shell: bash
      env:
        CI_MAKE_TARGET: smoke
      run: |
        echo "initial-PATH=$PATH" && \
        export "PATH=/c/mingw64/bin:/c/programdata/mingw64/mingw64/bin:$PATH" && \
        export MDBX_BUILD_OPTIONS=$(if [ "${{ matrix.build-type }}" = 'Debug' ]; then echo '-DMDBX_CHECKING=2 -DMDBX_DEBUG=1'; else echo '-DMDBX_CHECKING=0 -DMDBX_DEBUG=0'; fi) && \
        export MDBX_BUILD_CXX=$(if [ "${{ matrix.without_crt }}" = 'OFF' ]; then echo 'YES'; else echo 'NO'; fi) && \
        . ci/ci.sh "-G|MinGW Makefiles|-DCMAKE_BUILD_TYPE=${{ matrix.build-type }}|-DMDBX_BUILD_SHARED_LIBRARY:BOOL=${{ matrix.dll }}|-DMDBX_WITHOUT_MSVC_CRT:BOOL=${{ matrix.without_crt }}"
